apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamer-web
  template:
    metadata:
      labels:
        app: gamer-web
    spec:
      containers:
        - name: web-contnr
          image: manav1122/gamer-web:latest
