apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web-ns
spec:
  selector:
    app: gamer-web   # Use the appropriate label to match your pod
  ports:
    - protocol: TCP
      port: 80       # Port in the service
      targetPort: 80 # Port in the pod
  
